title: Ole Docs
description: Offsite mirror of Ole User Documents.
theme: just-the-docs

url: https://xyvir.github.io/OleDocs/

sass:
  custom: "_sass/custom/custom.scss"

  collections:
  desktop:
    output: true
  mobile:
    output: true
