title: Ole Docs
description: Offsite mirror of Ole User Documents.
theme: just-the-docs

url: https://xyvir.github.io/OleDocs/

sass:
  custom: "_sass/custom/custom.scss"

collections:
  desktop:
    output: true
  mobile:
    output: true

just_the_docs:
  collections:
    desktop:
      name: Desktop Docs
      nav_fold: true  # Makes it collapsible
    mobile:
      name: Mobile Docs
      nav_fold: true  # Makes it collapsible